- src: geerlingguy.certbot
- src: geerlingguy.composer
- src: geerlingguy.docker
- src: geerlingguy.git
- src: geerlingguy.nginx
- src: geerlingguy.nodejs
- src: geerlingguy.mysql
- src: geerlingguy.php
- src: geerlingguy.php-versions
- src: geerlingguy.redis
- src: geerlingguy.repo-epel
- src: geerlingguy.repo-remi
